### ISSUE TITLE
fatal error: QQmlExtensionPlugin: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by patricmutwiri** [gcompris/GCompris-qt#217]

**Comment by petitlapin** [comment]
Hi,

Do you have more information like the OS, Qt version, compilation log?

Thank you,

Johnny

**Comment by patricmutwiri** [comment]
Qt5.9.1/5.9.1/gcc_64/qml/Box2D $ make
g++ -c -m64 -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -IBox2D -I.moc -o .obj/box2dplugin.o box2dplugin.cpp
In file included from box2dplugin.cpp:28:0:
box2dplugin.h:29:31: fatal error: QQmlExtensionPlugin: No such file or directory
compilation terminated.
Makefile:1016: recipe for target '.obj/box2dplugin.o' failed
make: *** [.obj/box2dplugin.o] Error 1

**Comment by petitlapin** [comment]
I'm not sure why but it tries to compile with Qt4.8 instead of Qt5.
Can you share the CMakeCache.txt and the commands you typed (cmake ...) with the full log?

**Comment by patricmutwiri** [comment]
# This is the CMakeCache file.
# For build in directory: /home/patrick/Desktop/GCompris-qt
# It was generated by CMake: /usr/bin/cmake
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//No help, variable specified on the command line.
CMAKE_TOOLCHAIN_FILE:UNINITIALIZED=/usr/share/ECM/toolchain/Android.cmake

//No help, variable specified on the command line.
Qt5_DIR:UNINITIALIZED=


########################
# INTERNAL cache entries
########################

//This is the directory where this CMakeCache.txt was created
CMAKE_CACHEFILE_DIR:INTERNAL=/home/patrick/Desktop/GCompris-qt
//Major version of cmake used to create the current loaded cache
CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
//Minor version of cmake used to create the current loaded cache
CMAKE_CACHE_MINOR_VERSION:INTERNAL=5
//Patch version of cmake used to create the current loaded cache
CMAKE_CACHE_PATCH_VERSION:INTERNAL=1
//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=/usr/bin/cmake
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=/usr/bin/cpack
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=/usr/bin/ctest
//Path to CMake installation.
CMAKE_ROOT:INTERNAL=/usr/share/cmake-3.5

**Comment by petitlapin** [comment]
so yes, the error is that you don't compile with Qt5: Qt5_DIR:UNINITIALIZED=
Have you installed a Qt5 version? We have a page here to help install: http://gcompris.net/wiki/An_exercise_for_new_contributors

**Comment by petitlapin** [comment]
Hi, closing the issue as it seems to be a problem of Qt version
